/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Coins = bigint;
export interface DashboardStats {
  'totalEarned' : Coins,
  'recentHistory' : Array<EarningEvent>,
  'checkinStreak' : bigint,
  'spinCount' : bigint,
  'totalBalance' : Coins,
  'quizCount' : bigint,
}
export interface EarningEvent {
  'source' : EarningSource,
  'timestamp' : Timestamp,
  'amount' : Coins,
}
export type EarningSource = { 'checkin' : null } |
  { 'quiz' : null } |
  { 'spin' : null };
export type INR = bigint;
export interface QuizQuestion {
  'id' : bigint,
  'question' : string,
  'correctIndex' : bigint,
  'coinsReward' : Coins,
  'options' : Array<string>,
}
export type SessionId = string;
export type Timestamp = bigint;
export interface WithdrawalInput {
  'bankAccountNumber' : string,
  'ifscCode' : string,
  'accountHolderName' : string,
  'coinsRequested' : Coins,
}
export interface WithdrawalRequestPublic {
  'id' : bigint,
  'bankAccountNumber' : string,
  'status' : WithdrawalStatus,
  'ifscCode' : string,
  'createdAt' : Timestamp,
  'accountHolderName' : string,
  'inrAmount' : INR,
  'sessionId' : SessionId,
  'coinsRequested' : Coins,
}
export type WithdrawalResult = { 'ok' : WithdrawalRequestPublic } |
  { 'err' : string };
export type WithdrawalStatus = { 'pending' : null } |
  { 'rejected' : null } |
  { 'processed' : null };
export interface _SERVICE {
  'doCheckin' : ActorMethod<[SessionId], [] | [Coins]>,
  'doSpin' : ActorMethod<[SessionId], [] | [Coins]>,
  'getCheckinStreak' : ActorMethod<[SessionId], bigint>,
  'getCoinBalance' : ActorMethod<[SessionId], Coins>,
  'getDashboard' : ActorMethod<[SessionId], DashboardStats>,
  'getSpinInfo' : ActorMethod<[SessionId], { 'max' : bigint, 'used' : bigint }>,
  'getTodayQuiz' : ActorMethod<[SessionId], Array<QuizQuestion>>,
  'getWithdrawalHistory' : ActorMethod<
    [SessionId],
    Array<WithdrawalRequestPublic>
  >,
  'requestWithdrawal' : ActorMethod<
    [SessionId, WithdrawalInput],
    WithdrawalResult
  >,
  'submitQuizAnswer' : ActorMethod<[SessionId, bigint, bigint], [] | [Coins]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];