/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SessionId = IDL.Text;
export const Coins = IDL.Nat;
export const EarningSource = IDL.Variant({
  'checkin' : IDL.Null,
  'quiz' : IDL.Null,
  'spin' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const EarningEvent = IDL.Record({
  'source' : EarningSource,
  'timestamp' : Timestamp,
  'amount' : Coins,
});
export const DashboardStats = IDL.Record({
  'totalEarned' : Coins,
  'recentHistory' : IDL.Vec(EarningEvent),
  'checkinStreak' : IDL.Nat,
  'spinCount' : IDL.Nat,
  'totalBalance' : Coins,
  'quizCount' : IDL.Nat,
});
export const QuizQuestion = IDL.Record({
  'id' : IDL.Nat,
  'question' : IDL.Text,
  'correctIndex' : IDL.Nat,
  'coinsReward' : Coins,
  'options' : IDL.Vec(IDL.Text),
});
export const WithdrawalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'processed' : IDL.Null,
});
export const INR = IDL.Nat;
export const WithdrawalRequestPublic = IDL.Record({
  'id' : IDL.Nat,
  'bankAccountNumber' : IDL.Text,
  'status' : WithdrawalStatus,
  'ifscCode' : IDL.Text,
  'createdAt' : Timestamp,
  'accountHolderName' : IDL.Text,
  'inrAmount' : INR,
  'sessionId' : SessionId,
  'coinsRequested' : Coins,
});
export const WithdrawalInput = IDL.Record({
  'bankAccountNumber' : IDL.Text,
  'ifscCode' : IDL.Text,
  'accountHolderName' : IDL.Text,
  'coinsRequested' : Coins,
});
export const WithdrawalResult = IDL.Variant({
  'ok' : WithdrawalRequestPublic,
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  'doCheckin' : IDL.Func([SessionId], [IDL.Opt(Coins)], []),
  'doSpin' : IDL.Func([SessionId], [IDL.Opt(Coins)], []),
  'getCheckinStreak' : IDL.Func([SessionId], [IDL.Nat], ['query']),
  'getCoinBalance' : IDL.Func([SessionId], [Coins], ['query']),
  'getDashboard' : IDL.Func([SessionId], [DashboardStats], ['query']),
  'getSpinInfo' : IDL.Func(
      [SessionId],
      [IDL.Record({ 'max' : IDL.Nat, 'used' : IDL.Nat })],
      ['query'],
    ),
  'getTodayQuiz' : IDL.Func([SessionId], [IDL.Vec(QuizQuestion)], ['query']),
  'getWithdrawalHistory' : IDL.Func(
      [SessionId],
      [IDL.Vec(WithdrawalRequestPublic)],
      ['query'],
    ),
  'requestWithdrawal' : IDL.Func(
      [SessionId, WithdrawalInput],
      [WithdrawalResult],
      [],
    ),
  'submitQuizAnswer' : IDL.Func(
      [SessionId, IDL.Nat, IDL.Nat],
      [IDL.Opt(Coins)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SessionId = IDL.Text;
  const Coins = IDL.Nat;
  const EarningSource = IDL.Variant({
    'checkin' : IDL.Null,
    'quiz' : IDL.Null,
    'spin' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const EarningEvent = IDL.Record({
    'source' : EarningSource,
    'timestamp' : Timestamp,
    'amount' : Coins,
  });
  const DashboardStats = IDL.Record({
    'totalEarned' : Coins,
    'recentHistory' : IDL.Vec(EarningEvent),
    'checkinStreak' : IDL.Nat,
    'spinCount' : IDL.Nat,
    'totalBalance' : Coins,
    'quizCount' : IDL.Nat,
  });
  const QuizQuestion = IDL.Record({
    'id' : IDL.Nat,
    'question' : IDL.Text,
    'correctIndex' : IDL.Nat,
    'coinsReward' : Coins,
    'options' : IDL.Vec(IDL.Text),
  });
  const WithdrawalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'processed' : IDL.Null,
  });
  const INR = IDL.Nat;
  const WithdrawalRequestPublic = IDL.Record({
    'id' : IDL.Nat,
    'bankAccountNumber' : IDL.Text,
    'status' : WithdrawalStatus,
    'ifscCode' : IDL.Text,
    'createdAt' : Timestamp,
    'accountHolderName' : IDL.Text,
    'inrAmount' : INR,
    'sessionId' : SessionId,
    'coinsRequested' : Coins,
  });
  const WithdrawalInput = IDL.Record({
    'bankAccountNumber' : IDL.Text,
    'ifscCode' : IDL.Text,
    'accountHolderName' : IDL.Text,
    'coinsRequested' : Coins,
  });
  const WithdrawalResult = IDL.Variant({
    'ok' : WithdrawalRequestPublic,
    'err' : IDL.Text,
  });
  
  return IDL.Service({
    'doCheckin' : IDL.Func([SessionId], [IDL.Opt(Coins)], []),
    'doSpin' : IDL.Func([SessionId], [IDL.Opt(Coins)], []),
    'getCheckinStreak' : IDL.Func([SessionId], [IDL.Nat], ['query']),
    'getCoinBalance' : IDL.Func([SessionId], [Coins], ['query']),
    'getDashboard' : IDL.Func([SessionId], [DashboardStats], ['query']),
    'getSpinInfo' : IDL.Func(
        [SessionId],
        [IDL.Record({ 'max' : IDL.Nat, 'used' : IDL.Nat })],
        ['query'],
      ),
    'getTodayQuiz' : IDL.Func([SessionId], [IDL.Vec(QuizQuestion)], ['query']),
    'getWithdrawalHistory' : IDL.Func(
        [SessionId],
        [IDL.Vec(WithdrawalRequestPublic)],
        ['query'],
      ),
    'requestWithdrawal' : IDL.Func(
        [SessionId, WithdrawalInput],
        [WithdrawalResult],
        [],
      ),
    'submitQuizAnswer' : IDL.Func(
        [SessionId, IDL.Nat, IDL.Nat],
        [IDL.Opt(Coins)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };