/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface DashboardStats {
    totalEarned: Coins;
    recentHistory: Array<EarningEvent>;
    checkinStreak: bigint;
    spinCount: bigint;
    totalBalance: Coins;
    quizCount: bigint;
}
export type Coins = bigint;
export type Timestamp = bigint;
export interface WithdrawalRequestPublic {
    id: bigint;
    bankAccountNumber: string;
    status: WithdrawalStatus;
    ifscCode: string;
    createdAt: Timestamp;
    accountHolderName: string;
    inrAmount: INR;
    sessionId: SessionId;
    coinsRequested: Coins;
}
export interface QuizQuestion {
    id: bigint;
    question: string;
    correctIndex: bigint;
    coinsReward: Coins;
    options: Array<string>;
}
export interface EarningEvent {
    source: EarningSource;
    timestamp: Timestamp;
    amount: Coins;
}
export type WithdrawalResult = {
    __kind__: "ok";
    ok: WithdrawalRequestPublic;
} | {
    __kind__: "err";
    err: string;
};
export interface WithdrawalInput {
    bankAccountNumber: string;
    ifscCode: string;
    accountHolderName: string;
    coinsRequested: Coins;
}
export type SessionId = string;
export type INR = bigint;
export enum EarningSource {
    checkin = "checkin",
    quiz = "quiz",
    spin = "spin"
}
export enum WithdrawalStatus {
    pending = "pending",
    rejected = "rejected",
    processed = "processed"
}
export interface backendInterface {
    doCheckin(sessionId: SessionId): Promise<Coins | null>;
    doSpin(sessionId: SessionId): Promise<Coins | null>;
    getCheckinStreak(sessionId: SessionId): Promise<bigint>;
    getCoinBalance(sessionId: SessionId): Promise<Coins>;
    getDashboard(sessionId: SessionId): Promise<DashboardStats>;
    getSpinInfo(sessionId: SessionId): Promise<{
        max: bigint;
        used: bigint;
    }>;
    getTodayQuiz(sessionId: SessionId): Promise<Array<QuizQuestion>>;
    getWithdrawalHistory(sessionId: SessionId): Promise<Array<WithdrawalRequestPublic>>;
    requestWithdrawal(sessionId: SessionId, input: WithdrawalInput): Promise<WithdrawalResult>;
    submitQuizAnswer(sessionId: SessionId, questionId: bigint, selectedIndex: bigint): Promise<Coins | null>;
}
import type { Coins as _Coins, DashboardStats as _DashboardStats, EarningEvent as _EarningEvent, EarningSource as _EarningSource, INR as _INR, SessionId as _SessionId, Timestamp as _Timestamp, WithdrawalRequestPublic as _WithdrawalRequestPublic, WithdrawalResult as _WithdrawalResult, WithdrawalStatus as _WithdrawalStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async doCheckin(arg0: SessionId): Promise<Coins | null> {
        if (this.processError) {
            try {
                const result = await this.actor.doCheckin(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.doCheckin(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async doSpin(arg0: SessionId): Promise<Coins | null> {
        if (this.processError) {
            try {
                const result = await this.actor.doSpin(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.doSpin(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCheckinStreak(arg0: SessionId): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCheckinStreak(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCheckinStreak(arg0);
            return result;
        }
    }
    async getCoinBalance(arg0: SessionId): Promise<Coins> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoinBalance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoinBalance(arg0);
            return result;
        }
    }
    async getDashboard(arg0: SessionId): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboard(arg0);
                return from_candid_DashboardStats_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboard(arg0);
            return from_candid_DashboardStats_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSpinInfo(arg0: SessionId): Promise<{
        max: bigint;
        used: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getSpinInfo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSpinInfo(arg0);
            return result;
        }
    }
    async getTodayQuiz(arg0: SessionId): Promise<Array<QuizQuestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodayQuiz(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodayQuiz(arg0);
            return result;
        }
    }
    async getWithdrawalHistory(arg0: SessionId): Promise<Array<WithdrawalRequestPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWithdrawalHistory(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWithdrawalHistory(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async requestWithdrawal(arg0: SessionId, arg1: WithdrawalInput): Promise<WithdrawalResult> {
        if (this.processError) {
            try {
                const result = await this.actor.requestWithdrawal(arg0, arg1);
                return from_candid_WithdrawalResult_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestWithdrawal(arg0, arg1);
            return from_candid_WithdrawalResult_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitQuizAnswer(arg0: SessionId, arg1: bigint, arg2: bigint): Promise<Coins | null> {
        if (this.processError) {
            try {
                const result = await this.actor.submitQuizAnswer(arg0, arg1, arg2);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitQuizAnswer(arg0, arg1, arg2);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_DashboardStats_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DashboardStats): DashboardStats {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_EarningEvent_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EarningEvent): EarningEvent {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_EarningSource_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EarningSource): EarningSource {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalRequestPublic_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalRequestPublic): WithdrawalRequestPublic {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalResult_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalResult): WithdrawalResult {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalStatus): WithdrawalStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Coins]): Coins | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    bankAccountNumber: string;
    status: _WithdrawalStatus;
    ifscCode: string;
    createdAt: _Timestamp;
    accountHolderName: string;
    inrAmount: _INR;
    sessionId: _SessionId;
    coinsRequested: _Coins;
}): {
    id: bigint;
    bankAccountNumber: string;
    status: WithdrawalStatus;
    ifscCode: string;
    createdAt: Timestamp;
    accountHolderName: string;
    inrAmount: INR;
    sessionId: SessionId;
    coinsRequested: Coins;
} {
    return {
        id: value.id,
        bankAccountNumber: value.bankAccountNumber,
        status: from_candid_WithdrawalStatus_n12(_uploadFile, _downloadFile, value.status),
        ifscCode: value.ifscCode,
        createdAt: value.createdAt,
        accountHolderName: value.accountHolderName,
        inrAmount: value.inrAmount,
        sessionId: value.sessionId,
        coinsRequested: value.coinsRequested
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalEarned: _Coins;
    recentHistory: Array<_EarningEvent>;
    checkinStreak: bigint;
    spinCount: bigint;
    totalBalance: _Coins;
    quizCount: bigint;
}): {
    totalEarned: Coins;
    recentHistory: Array<EarningEvent>;
    checkinStreak: bigint;
    spinCount: bigint;
    totalBalance: Coins;
    quizCount: bigint;
} {
    return {
        totalEarned: value.totalEarned,
        recentHistory: from_candid_vec_n4(_uploadFile, _downloadFile, value.recentHistory),
        checkinStreak: value.checkinStreak,
        spinCount: value.spinCount,
        totalBalance: value.totalBalance,
        quizCount: value.quizCount
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    source: _EarningSource;
    timestamp: _Timestamp;
    amount: _Coins;
}): {
    source: EarningSource;
    timestamp: Timestamp;
    amount: Coins;
} {
    return {
        source: from_candid_EarningSource_n7(_uploadFile, _downloadFile, value.source),
        timestamp: value.timestamp,
        amount: value.amount
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    rejected: null;
} | {
    processed: null;
}): WithdrawalStatus {
    return "pending" in value ? WithdrawalStatus.pending : "rejected" in value ? WithdrawalStatus.rejected : "processed" in value ? WithdrawalStatus.processed : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _WithdrawalRequestPublic;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: WithdrawalRequestPublic;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_WithdrawalRequestPublic_n10(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    checkin: null;
} | {
    quiz: null;
} | {
    spin: null;
}): EarningSource {
    return "checkin" in value ? EarningSource.checkin : "quiz" in value ? EarningSource.quiz : "spin" in value ? EarningSource.spin : value;
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EarningEvent>): Array<EarningEvent> {
    return value.map((x)=>from_candid_EarningEvent_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WithdrawalRequestPublic>): Array<WithdrawalRequestPublic> {
    return value.map((x)=>from_candid_WithdrawalRequestPublic_n10(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
